### ISSUE TITLE
html prettify 未作 空值校验 label:bug 

### ISSUE THREAD

**Issue by symbols-ink** [ulivz/vuepress-plugin-yuque#1]
解析一篇无内容文档时报的错误

```
TypeError: Cannot read property 'replace' of null
    at prune (/node_modules/vuepress-plugin-yuque/lib/html.js:50:6)
    at prettify (/node_modules/vuepress-plugin-yuque/lib/html.js:39:10)
    at ready (/node_modules/vuepress-plugin-yuque/lib/index.js:129:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

> /lib/index.js:129
```js
        let postContent
        if (status && status === 404) {
          postContent = `# ${title}\n > 此文档尚未创建`
        } else {
          if (useMarkdown || data.format === 'markdown') {
            postContent = data.body
          } else {
            postContent = prettify(data.body_html)  // 这里 data.body_html 可能为 null
          }
        }
```

```js
function prettify(html) {
  html = prune(html)
  const $ = cheerio.load(html, {
    // ref: https://github.com/cheeriojs/cheerio/issues/565
    decodeEntities: false
  })
  transformHeaders($)
  return $('body').html()
}

function prune(html) {  // 这里 html 可能传入 null
  return html
    .replace(/<p><br\s\/><\/p>/g, '')
    .replace(/<p><span><br\s\/><\/span><\/p>/g, '')
}
```

**Comment by ulivz** [comment]
Thanks, fixed at 11102743b25a65e53cfa052cb580754a897bab35
