### ISSUE TITLE
按照教程来操作，用教程上面的 repoId 或者 repoUrl 都是报错。

### ISSUE THREAD

**Issue by zaleGZL** [ulivz/vuepress-plugin-yuque#36]
```
yarn run v1.22.0
$ vuepress dev .
wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin yuque (i.e. "vuepress-plugin-yuque") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
✖ Please check your repoId: 214564 response: {"status":401,"message":"Unauthorized"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by zaleGZL** [comment]
```
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin yuque (i.e. "vuepress-plugin-yuque") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
error vuepress-plugin-yuque apply ready failed.
AssertionError [ERR_ASSERTION]: [CANNOT_FIND_GROUP] Cannot infer repoId from repoUrl: https://www.yuque.com/vuepress/vuepress-plugin-yuque
    at Function.inferRepoByUrl (/Users/guozeling/workspace/zale/zale_website/node_modules/vuepress-plugin-yuque/lib/yuque.js:110:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ready (/Users/guozeling/workspace/zale/zale_website/node_modules/vuepress-plugin-yuque/lib/index.js:63:28)
    at async AsyncOption.asyncApply (/Users/guozeling/workspace/zale/zale_website/node_modules/@vuepress/core/lib/node/plugin-api/abstract/AsyncOption.js:33:15)
    at async PluginAPI.applyAsyncOption (/Users/guozeling/workspace/zale/zale_website/node_modules/@vuepress/core/lib/node/plugin-api/index.js:277:5)
    at async App.process (/Users/guozeling/workspace/zale/zale_website/node_modules/@vuepress/core/lib/node/App.js:123:5)
    at async dev (/Users/guozeling/workspace/zale/zale_website/node_modules/@vuepress/core/lib/index.js:17:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fychinesepjj** [comment]
现在语雀不允许匿名访问，需要申请token才能访问，否则是401报错

**Comment by zaleGZL** [comment]
请教下， token 是配置在哪里，我配置在这个位置还是不行。
