### ISSUE TITLE
build error  Cannot infer repoId from repoUrl

### ISSUE THREAD

**Issue by qixiaobo** [ulivz/vuepress-plugin-yuque#42]
```plain
AssertionError [ERR_ASSERTION]: [CANNOT_FIND_GROUP] Cannot infer repoId from repoUrl: https://www.yuque.com/ant-design/course
    at Function.inferRepoByUrl (/Users/qixiaobo/work/yuque-doc/node_modules/vuepress-plugin-yuque/lib/yuque.js:110:5)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

```json
{
  "name": "yuque-doc",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "vuepress": "^1.0.0-rc.1",
    "vuepress-plugin-yuque": "^0.6.1"
  },
  "scripts": {
   "dev": "vuepress dev .",
   "build": "vuepress build ."
 }
}
```

**Comment by qixiaobo** [comment]
I found yuque changes its security policy.

> 出于对知识库安全性的调整，使用第三方 API 访问知识库，需要传入环境变量 YUQUE_TOKEN，在语雀上点击 个人头像 -> 设置 -> Token 即可获取。

We should put token here, it will be fine
