### ISSUE TITLE
一个不知名的错误

### ISSUE THREAD

**Issue by echoxxzhang** [ulivz/vuepress-plugin-yuque#64]
按照“快速上手”，我已经完成前面的步骤，但是执行yarn dev时，就抛出这样的错误。

Error: Cannot find module '@vuepress/shared-utils'
Require stack:
- E:\Github\my-site\node_modules\@vuepress\plugin-medium-zoom\index.js
- E:\Github\my-site\node_modules\@vuepress\core\lib\app\resolvePlugin.js
- E:\Github\my-site\node_modules\@vuepress\core\lib\app\normalizePlugin.js
- E:\Github\my-site\node_modules\@vuepress\core\lib\app\appUse.js
- E:\Github\my-site\node_modules\@vuepress\core\lib\app\index.js
- E:\Github\my-site\node_modules\@vuepress\core\lib\index.js
- E:\Github\my-site\node_modules\@vuepress\cli\lib\commands\build\build.js
- E:\Github\my-site\node_modules\@vuepress\cli\lib\commands\build\index.js
- E:\Github\my-site\node_modules\@vuepress\cli\lib\commands\index.js
- E:\Github\my-site\node_modules\@vuepress\cli\lib\index.js
- E:\Github\my-site\node_modules\@vuepress\cli\bin\vuepress.js
- E:\Github\my-site\node_modules\vuepress\bin\vuepress.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\Github\my-site\node_modules\@vuepress\plugin-medium-zoom\index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
error Command failed with exit code 1.

**Comment by geekape** [comment]
安装下这些包就好了，注意Node版本用12.x的会构建失败，改用10.x就可以
